name: ella
services:
  workspace:
    image: ghcr.io/ppoi/devenv-type-charlie:20240513-01
    volumes:
      - workspaces:/workspaces
      - ../:/workspaces/devenv
      - devcerts-volume:/certs
      - /run/podman/podman.sock:/var/run/docker.sock
    command: /opt/setup-tools/code-workspace.sh ella
volumes:
  workspaces:
  devcerts-volume:
    external: true
